import os
import subprocess
import pyttsx3
import webbrowser
import speech_recognition as sr
import pythoncom

print("Webbrowser is getting installed")
os.system("pip install webbrowser")
print("-------------------------------------------------")
print("Pyttssx3 is getting installed")
os.system("pip install pyttsx3")
print("-------------------------------------------------")
print("Speech Recognition is getting installed")
os.system("pip install SpeechRecognition")
print("-------------------------------------------------")
print("Pythoncom is getting installed")
os.system("pip install pythoncom")
print("-------------------------------------------------")
print("Subprocess is getting installed")
os.system("pip install subprocess")
print("-------------------------------------------------")
print("Wikipedia is getting installed")
os.system("pip install wikipedia")
print("-------------------------------------------------")
print("Pyaudio is getting installed")
os.system("pip install pyaudio")
print("-------------------------------------------------")
print("DateTime is getting installed")
os.system("pip install datetime")
print("-------------------------------------------------")
print("Time is getting installed")
os.system("pip install time")
print("-------------------------------------------------")
print("Pygame is getting installed")
os.system("pip install pygame")
print("-------------------------------------------------")
print("gTTS is getting installed")
os.system("pip install gTTS")
print("-------------------------------------------------")
print("odules are getting installed")
os.system("pip install modules")
print("-------------------------------------------------")
print("pyautogui is getting installed")
os.system("py -m pip install pyautogui")
print("-------------------------------------------------")
print("pyutogui is getting installed")
os.system("pip install PyAutoGUI")
print("-------------------------------------------------")
print("opencv is getting installed")
os.system("py -m pip install opencv-python")
print("-------------------------------------------------")
print("All done...")